<a href="https://colab.research.google.com/github/Shruti-Chatre/Student_Performance_Analyzer/blob/main/Student_Performance_Analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
student_data = pd.read_csv("student.csv")

In [3]:
student_data

     Name  Maths  Science  English
0   Aarav     85       78       90
1    Siya     45       56       40
2   Rohan     25       35       30
3   Anaya     95       92       88
4  Vivaan     67       70       72
5    Diya     38       42       36
6   Kabir     80       75       85
7   Meera     55       60       58

In [4]:
print(student_data)

     Name  Maths  Science  English
0   Aarav     85       78       90
1    Siya     45       56       40
2   Rohan     25       35       30
3   Anaya     95       92       88
4  Vivaan     67       70       72
5    Diya     38       42       36
6   Kabir     80       75       85
7   Meera     55       60       58

In [5]:
student_data.head()

     Name  Maths  Science  English
0   Aarav     85       78       90
1    Siya     45       56       40
2   Rohan     25       35       30
3   Anaya     95       92       88
4  Vivaan     67       70       72

In [6]:
student_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      object
 1   Maths    8 non-null      int64
 2   Science  8 non-null      int64
 3   English  8 non-null      int64
dtypes: int64(3), object(1)
memory usage: 388.0+ bytes

In [7]:
# Statistical Summary
student_data.describe()

           Maths    Science   English
count   8.000000   8.000000   8.00000
mean   61.250000  63.500000  62.37500
std    24.627221  19.048809  24.74982
min    25.000000  35.000000  30.00000
25%    43.250000  52.500000  39.00000
50%    61.000000  65.000000  65.00000
75%    81.250000  75.750000  85.75000
max    95.000000  92.000000  90.00000

In [8]:
# Selecting one column
student_data["Maths"]

0    85
1    45
2    25
3    95
4    67
5    38
6    80
7    55
Name: Maths, dtype: int64

In [9]:
# Selecting multiple columns
student_data[["Name", "Maths"]]

     Name  Maths
0   Aarav     85
1    Siya     45
2   Rohan     25
3   Anaya     95
4  Vivaan     67
5    Diya     38
6   Kabir     80
7   Meera     55

In [10]:
student_data[student_data["Maths"] > 50]

     Name  Maths  Science  English
0   Aarav     85       78       90
3   Anaya     95       92       88
4  Vivaan     67       70       72
6   Kabir     80       75       85
7   Meera     55       60       58

In [11]:
student_data[student_data["Maths"] < 40]

    Name  Maths  Science  English
2  Rohan     25       35       30
5   Diya     38       42       36

In [12]:
student_data["Maths"].mean()

np.float64(61.25)

In [13]:
student_data["Science"].max()

92

In [14]:
student_data["English"].min()

30

In [15]:
student_data["Total_marks"] = student_data["Maths"] + student_data["English"] + student_data["Science"]

In [16]:
student_data

     Name  Maths  Science  English  Total_marks
0   Aarav     85       78       90          253
1    Siya     45       56       40          141
2   Rohan     25       35       30           90
3   Anaya     95       92       88          275
4  Vivaan     67       70       72          209
5    Diya     38       42       36          116
6   Kabir     80       75       85          240
7   Meera     55       60       58          173

In [17]:
student_data.sort_values(by = "Total_marks", inplace = True, ascending = False)

In [19]:
student_data["Percentage"] = (student_data["Total_marks"]/300)*100
student_data

     Name  Maths  Science  English  Total_marks  Percentage
3   Anaya     95       92       88          275   91.666667
0   Aarav     85       78       90          253   84.333333
6   Kabir     80       75       85          240   80.000000
4  Vivaan     67       70       72          209   69.666667
7   Meera     55       60       58          173   57.666667
1    Siya     45       56       40          141   47.000000
5    Diya     38       42       36          116   38.666667
2   Rohan     25       35       30           90   30.000000

In [20]:
student_data["Percentage"] = round(student_data["Percentage"], 2)

In [21]:
student_data

     Name  Maths  Science  English  Total_marks  Percentage
3   Anaya     95       92       88          275       91.67
0   Aarav     85       78       90          253       84.33
6   Kabir     80       75       85          240       80.00
4  Vivaan     67       70       72          209       69.67
7   Meera     55       60       58          173       57.67
1    Siya     45       56       40          141       47.00
5    Diya     38       42       36          116       38.67
2   Rohan     25       35       30           90       30.00

In [22]:
student_data["Results"] = student_data["Percentage"].apply(lambda x : "Pass" if x >= 40 else "Fail")

In [23]:
student_data

     Name  Maths  Science  English  Total_marks  Percentage Results
3   Anaya     95       92       88          275       91.67    Pass
0   Aarav     85       78       90          253       84.33    Pass
6   Kabir     80       75       85          240       80.00    Pass
4  Vivaan     67       70       72          209       69.67    Pass
7   Meera     55       60       58          173       57.67    Pass
1    Siya     45       56       40          141       47.00    Pass
5    Diya     38       42       36          116       38.67    Fail
2   Rohan     25       35       30           90       30.00    Fail

In [24]:
student_data.to_csv("updated_students.csv", index = False)